language: scala
dist: trusty
sudo: false

scala:
  - 2.11.11

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.12.2
      jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.coursier

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageOff
  - |
    if [[ "$TRAVIS_BRANCH" = "master" && $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
      gpg_key_path=$HOME/.gnupg
      mkdir -p $gpg_key_path
      echo $GPG_KEY | base64 --decode > $gpg_key_path/secring.gpg
      sbt publishSigned
    fi

after_script:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - codecov
